variables:
  VERSION: 1.2.0

stages:
  - style
  - build
  - test

include:
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - project: cjburchell/pipeline_templates
    ref: master
    file:
      - '/templates/.docker-build.yml'
      - '/templates/.go-build-14.yml'
